DEF VAR h_res AS MEMPTR.
DEF VAR len AS LONG.

SET-SIZE(h_res) = 1024.
RUN sprintf(INPUT-OUTPUT h_res, "Ana are %s", "mere", OUTPUT len).
MESSAGE GET-STRING(h_res, 1)
    VIEW-AS ALERT-BOX INFO BUTTONS OK.

PROCEDURE sprintf EXTERNAL "C:\Windows\System32\msvcrt.dll" CDECL:
    DEFINE INPUT-OUTPUT PARAMETER res AS MEMPTR.
    DEFINE INPUT PARAMETER par AS CHARACTER.
    DEFINE INPUT PARAMETER str AS CHARACTER.
    DEFINE RETURN PARAMETER len AS LONG.
END.


